module.exports = {
  Addfullscreen: {
    width: '100%',
    height: '100%',
    backgroundColor: '#5a55ca',
    flexDirection: 'column',
  },
  flexBox: {
    // margin: 15,
    flexDirection: 'columns',
  },
  Addsubscreen: {
    marginTop: 20,
    height: '17%',
    flexDirection: 'row',
    width: 110,
    // justifyContent: 'space-between',
  },

  addSecondScreen: {
    height: '85%',
    width: '100%',
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 30,
    paddingTop: 17,
    flexDirection: 'column',
  },
  AddtitleText: {
    // width: '40%',
    height: 50,
    maxWidth: 300,
    fontSize: 22,
    borderRadius: 30,
    fontFamily: 'Poppins-Bold',
    color: 'white',
  },
  dateInput: {
    // margin: 12,
    borderColor: '#8d98b0',
    // boxSizing: "borderBox",
    width: '96%',
    borderBottomWidth: 1,
    color: 'black',
    paddingVertical: 0,
  },
  input: {
    // margin: 12,
    borderColor: '#8d98b0',
    // boxSizing: "borderBox",

    borderBottomWidth: 1,
    color: 'black',
    paddingVertical: 0,
    fontFamily: 'Poppins-Regular',
  },
  Emailinput: {
    // margin: 12,
    borderColor: '#8d98b0',
    // boxSizing: "borderBox",
    width: '94%',
    marginBottom: 10,
    borderBottomWidth: 1,
    color: 'black',
    paddingVertical: 0,
    fontFamily: 'Poppins-Regular',
  },
  passwordinput: {
    // margin: 12,
    borderColor: '#8d98b0',
    // boxSizing: "borderBox",
    // border: 'none',
    width: '94%',
    borderBottomWidth: 1,
    color: 'black',
    paddingVertical: 0,
    fontFamily: 'Poppins-Regular',
  },
  labelStyle: {
    color: 'black',
    marginLeft: 4,
    color: '#8d98b0',
    fontFamily: 'Poppins-Medium',
  },

  commonPadding: {},
  avatarText: {
    color: '#c2c9d7',
    fontFamily: 'Poppins-Regular',
  },
  timeContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginLeft: 43,
  },
  timeInput: {
    // margin: 12,
    borderColor: '#8d98b0',
    // boxSizing: "borderBox",
    borderBottomWidth: 1,
    color: 'black',
    width: '100%',
    paddingVertical: 0,
  },
  submitBtn: {
    width: '100%',
    marginTop: 20,
  },

  Loginsubscreen: {
    flexDirection: 'row',
    width: 110,
    height: '19%',
  },
  loginSecondScreen: {
    height: '90%',
    width: '100%',
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 30,
    paddingTop: 67,
    flexDirection: 'column',
  },
 registerSecondScreen: {
    height: '90%',
    width: '100%',
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 30,
    flexDirection: 'column',
  },
  emaillabelStyle: {
    color: 'black',
    marginLeft: 4,
    color: '#8d98b0',
    fontFamily: 'Poppins-Medium',
  },
};
