const {Dimensions} = require('react-native');
const {LinearGradient} = require('react-native-svg');

const deviceHeight = Dimensions.get('window').height;
const deviceWidth = Dimensions.get('window').width;
module.exports = {
  Addfullscreen: {
    height: deviceHeight,
    widht: deviceWidth,
    flex: 1,
    backgroundColor: '#1b1b1b',
  },
  btmeditsheet: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1b1b1b',
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  addteamcontainerStyle: {
    width: deviceWidth * 0.85,
    height: deviceHeight * 0.45,
    // borderWidth: 1,
    // borderColor: 'black',
    backgroundColor: '#1b1b1b',
    padding: 10,
    borderRadius: 20,
    justifyContent: 'center',
    position: 'absolute',
    top: (deviceHeight - deviceHeight * 0.45) / 2,
    left: (deviceWidth - deviceWidth * 0.85) / 2,
  },
  flexBox: {
    flexDirection: 'columns',
  },
  Addsubscreen: {
    // flex: 1,
    height: deviceHeight / 8,
    marginBottom: 20,
  },

  modalSecondScreen: {
    // backgroundColor: 'white',
    // padding: 30,
    // marginLeft: 21,
    // marginRight: 21,
    // marginTop:25,
    width: '100%',
    height: '100%',
    backgroundColor: 'black',
    flexDirection: 'column',
  },
  addSecondScreen: {
    backgroundColor: 'black',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 30,
    // paddingTop: 7,
    flexDirection: 'column',
  },
  error: {
    color: 'red',
  },
  AddtitleText: {
    height: 50,
    maxWidth: 300,
    fontSize: 22,
    borderRadius: 30,
    fontFamily: 'Poppins-Bold',
    color: '#1b1b1b',
  },
  dateInput: {
    borderColor: '#6DED65',
    width: '96%',
    borderBottomWidth: 1,
    color: 'white',
    paddingVertical: 0,
  },
  input: {
    borderColor: '#6DED65',
    borderBottomWidth: 1,
    color: 'white',
    paddingVertical: 0,
    fontFamily: 'Poppins-Regular',
  },
  Emailinput: {
    width: '100%',
    marginBottom: 10,
    borderBottomWidth: 1,
    paddingVertical: 0,
    fontFamily: 'Poppins-Regular',
    alignSelf: 'flex-start',
  },
  passwordinput: {
    borderColor: '#8d98b0',
    width: '94%',
    borderBottomWidth: 1,
    color: '#b3caf3',
    paddingVertical: 0,
    height: 32,
    fontFamily: 'Poppins-Regular',
  },
  labelStyle: {
    color: 'white',
    marginLeft: 4,
    color: '#6DED65',
    fontFamily: 'Poppins-Medium',
    marginTop: 15,
    alignSelf: 'flex-start',
  },

  commonPadding: {},
  avatarText: {
    color: '#6DED65',
    fontFamily: 'Poppins-Regular',
  },
  timeContainer: {
    // width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    // marginLeft: 43,
    marginTop: 10,
  },
  timeInput: {
    borderColor: '#6DED65',
    borderBottomWidth: 1,
    color: 'black',
    width: '100%',
    paddingVertical: 0,
  },
  submitBtn1: {
    width: '100%',
    marginTop: 20,
    backgroundColor: '#6DED65',
    color: 'white',
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    height: 45,
  },
  loginText: {
    fontSize: 16,
    color: '#1b1b1b',
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
  },
  sendOtp: {
    width: '100%',
    marginTop: 20,
    backgroundColor: '#6DED65',
    color: 'black',
    marginBottom: 315,
  },

  AddTeamsubscreen: {
    flex: 1,
    marginBottom: 20,
  },
  Loginsubscreen: {
    // flex: 1,
    height: deviceHeight / 8,
    marginBottom: 20,
  },
  loginSecondScreen: {
    // height: '100%',
    flex: 1,
    width: '100%',
    backgroundColor: '#1b1b1b',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 30,
    paddingTop: 67,
    flexDirection: 'column',
  },
  registerSecondScreen: {
    flex: 1,
    height: deviceHeight / 1.15,
    width: '100%',
    backgroundColor: '#1b1b1b',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 30,
    // marginTop:10,
    flexDirection: 'column',
  },
  AddTeamSecondScreen: {
    // height: '90%',
    flex: 2,
    // width: '100%',
    backgroundColor: '#6DED65',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 30,
    flexDirection: 'column',
  },
  emaillabelStyle: {
    marginLeft: 4,
    color: '#6DED65',
    fontFamily: 'Poppins-Medium',
    marginTop: 15,
  },

  containerStyle: {
    backgroundColor: 'white',
    padding: 20,
    height: '100%',
    width: '70%',
    borderRadius: 20,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
  },
  modalTital: {
    fontFamily: 'Poppins-SemiBold',
    color: 'black',
    fontSize: 20,
  },
  modalSubtital: {
    paddingTop: 20,
    fontFamily: 'Poppins-Light',
    textAlign: 'center',
    color: 'grey',
  },

  orText: {
    fontFamily: 'Poppins-Regular',
    color: 'black',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 5,
  },
  lineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    marginTop: 15,
  },
  grayLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'gray',
    marginHorizontal: 10,
  },
  orText: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // confirmationModal:{
  //   background:'blueGrey100',
  //   backgroundColor: 'white',
  //   padding: 20,
  //   height: '100%',
  //   width: '100%',
  //   borderRadius: 18,
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  //   alignItems: 'center',
  //   zindex : 50
  // },
  confirmationModal: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 8,
    height: '40%',
    width: '100%',
    zindex: 70,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    width: '100%',
  },

  confirmButton: {
    width: 100,
    alignSelf: 'center',
  },
  cancelButton: {
    width: 100,
    alignSelf: 'center',
  },
  confomationtex: {
    color: 'black',
    fontFamily: 'Poppins-Regular',
  },
};
